// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIVMDUlAbfHv5DQnAjZynMRmGpGUeP55Y',
    appId: '1:205263360781:web:95463b8bf65ed895879644',
    messagingSenderId: '205263360781',
    projectId: 'projetoportaria-1de8d',
    authDomain: 'projetoportaria-1de8d.firebaseapp.com',
    storageBucket: 'projetoportaria-1de8d.firebasestorage.app',
    measurementId: 'G-3Y0H1GFSWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnVFVUek5Bz6osWZz5y96K3ZLVb0HEL1o',
    appId: '1:205263360781:android:4b75aa653a7c3299879644',
    messagingSenderId: '205263360781',
    projectId: 'projetoportaria-1de8d',
    storageBucket: 'projetoportaria-1de8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBucyLQBK9ANAEneOkkUWrnqOcLkFyjdes',
    appId: '1:205263360781:ios:a01d8b0d5d7c049a879644',
    messagingSenderId: '205263360781',
    projectId: 'projetoportaria-1de8d',
    storageBucket: 'projetoportaria-1de8d.firebasestorage.app',
    iosBundleId: 'com.example.portariaCondominio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBucyLQBK9ANAEneOkkUWrnqOcLkFyjdes',
    appId: '1:205263360781:ios:a01d8b0d5d7c049a879644',
    messagingSenderId: '205263360781',
    projectId: 'projetoportaria-1de8d',
    storageBucket: 'projetoportaria-1de8d.firebasestorage.app',
    iosBundleId: 'com.example.portariaCondominio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIVMDUlAbfHv5DQnAjZynMRmGpGUeP55Y',
    appId: '1:205263360781:web:a88c478bf3bd6488879644',
    messagingSenderId: '205263360781',
    projectId: 'projetoportaria-1de8d',
    authDomain: 'projetoportaria-1de8d.firebaseapp.com',
    storageBucket: 'projetoportaria-1de8d.firebasestorage.app',
    measurementId: 'G-L4BMXBPC2L',
  );

}